package co.nroma.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import co.nroma.db.PoemFavoriteEntity;

import co.nroma.db.PoemFavoriteEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig poemFavoriteEntityDaoConfig;

    private final PoemFavoriteEntityDao poemFavoriteEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        poemFavoriteEntityDaoConfig = daoConfigMap.get(PoemFavoriteEntityDao.class).clone();
        poemFavoriteEntityDaoConfig.initIdentityScope(type);

        poemFavoriteEntityDao = new PoemFavoriteEntityDao(poemFavoriteEntityDaoConfig, this);

        registerDao(PoemFavoriteEntity.class, poemFavoriteEntityDao);
    }
    
    public void clear() {
        poemFavoriteEntityDaoConfig.clearIdentityScope();
    }

    public PoemFavoriteEntityDao getPoemFavoriteEntityDao() {
        return poemFavoriteEntityDao;
    }

}
